#!/usr/bin/env python3
# ruff: noqa: E501 — the strings are prose and CSS; wrapping them would not help a reader
"""the-loop logo options (issue-398): five brush-drawn SVG marks from one generator.

Usage:

    python3 generate.py            write the five SVGs and the gallery next to this file
    python3 generate.py --check    verify the files on disk are exactly what this script
                                   makes, well-formed, self-contained and titled

Standard library only. Every mark is one or more *strokes*: a centreline (a parametric
curve, or a spline through hand-placed points) outlined by a flat brush — thick across
the nib and thin along it, pressed harder mid-stroke, lifted in and out — and emitted as
one filled path. Nothing depends on stroke rendering, filters or fonts, so the files
render the same in a browser, a README, a favicon and an image tool. Change a parameter,
re-run, and every file is regenerated byte-for-byte.

Round 1 (git history) drew five loop *structures* with a wobbling, over-drawn hand; the
owner's review asked for character and less stress on the hand-drawn part. Round 2 keeps
the hand — a brush, held at an angle, lifted where it stops — and gives each mark a
personality instead of a diagram.
"""

from __future__ import annotations

import bisect
import math
import random
import re
import sys
import xml.etree.ElementTree as ET
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIZE = 256.0
C = SIZE / 2

# The palette: one warm ink, five muted accents, paper and slate for the two grounds.
INK = "#3f3a33"
INK_ON_SLATE = "#e9e3d7"
PAPER = "#f5f0e6"
SLATE = "#22252a"
SAGE = "#8a9c84"
DUSK = "#7f93a5"
CLAY = "#c48a6c"
OCHRE = "#c7a86b"
MAUVE = "#9d8a9f"

Point = tuple[float, float]
Curve = Callable[[float], Point]
Width = Callable[[float, float], float]  # (u along the stroke, tangent angle) → width


# --------------------------------------------------------------------------- geometry


def fmt(p: Point) -> str:
    return f"{p[0]:.1f} {p[1]:.1f}"


def smoothstep(x: float) -> float:
    x = min(1.0, max(0.0, x))
    return x * x * (3 - 2 * x)


class Wobble:
    """Seeded sideways noise: a few integer harmonics of the stroke's own period. Round
    2 uses it sparingly — a hair of warmth, never a tremor."""

    def __init__(self, rng: random.Random, amp: float, harmonics=(2, 3, 5)) -> None:
        self.terms = [
            (amp / (i + 1), h, rng.uniform(0, math.tau))
            for i, h in enumerate(harmonics)
        ]

    def __call__(self, u: float) -> float:
        return sum(a * math.sin(math.tau * h * u + p) for a, h, p in self.terms)


def tangent(curve: Curve, u: float, du: float = 1e-3) -> tuple[float, float]:
    ax, ay = curve(u - du)
    bx, by = curve(u + du)
    tx, ty = bx - ax, by - ay
    norm = math.hypot(tx, ty) or 1.0
    return tx / norm, ty / norm


def trace(
    curve: Curve,
    u0: float,
    u1: float,
    n: int,
    wobble: Wobble | None = None,
) -> list[Point]:
    """Sample `curve` on [u0, u1], pushing each sample along its normal by the wobble."""
    pts: list[Point] = []
    for i in range(n + 1):
        u = u0 + (u1 - u0) * i / n
        x, y = curve(u)
        tx, ty = tangent(curve, u)
        off = wobble(u) if wobble else 0.0
        pts.append((x - ty * off, y + tx * off))
    return pts


def spline(pts: list[Point], closed: bool) -> str:
    """Catmull-Rom through the points, emitted as cubic Béziers."""
    n = len(pts)

    def at(i: int) -> Point:
        return pts[i % n] if closed else pts[min(max(i, 0), n - 1)]

    out = [f"M{fmt(pts[0])}"]
    for i in range(n if closed else n - 1):
        p0, p1, p2, p3 = at(i - 1), at(i), at(i + 1), at(i + 2)
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        out.append(f"C{fmt(c1)} {fmt(c2)} {fmt(p2)}")
    out.append("Z")
    return "".join(out)


def catmull_points(keys: list[Point], per_seg: int = 16) -> list[Point]:
    """Dense samples of the open Catmull-Rom curve through hand-placed `keys`."""
    n = len(keys)

    def at(i: int) -> Point:
        return keys[min(max(i, 0), n - 1)]

    out: list[Point] = []
    for i in range(n - 1):
        (x0, y0), (x1, y1), (x2, y2), (x3, y3) = at(i - 1), at(i), at(i + 1), at(i + 2)
        for k in range(per_seg):
            t = k / per_seg
            t2, t3 = t * t, t * t * t
            x = 0.5 * (
                2 * x1
                + (-x0 + x2) * t
                + (2 * x0 - 5 * x1 + 4 * x2 - x3) * t2
                + (-x0 + 3 * x1 - 3 * x2 + x3) * t3
            )
            y = 0.5 * (
                2 * y1
                + (-y0 + y2) * t
                + (2 * y0 - 5 * y1 + 4 * y2 - y3) * t2
                + (-y0 + 3 * y1 - 3 * y2 + y3) * t3
            )
            out.append((x, y))
    out.append(keys[-1])
    return out


def by_arc_length(points: list[Point]) -> tuple[Curve, float]:
    """A curve through dense `points`, parameterised by arc length on [0, 1], so the
    brush's pressure and lifts are even along the stroke. Returns (curve, length)."""
    lengths = [0.0]
    for (x0, y0), (x1, y1) in zip(points, points[1:], strict=False):
        lengths.append(lengths[-1] + math.hypot(x1 - x0, y1 - y0))
    total = lengths[-1] or 1.0

    def f(u: float) -> Point:
        s = min(max(u, 0.0), 1.0) * total
        i = min(max(bisect.bisect_right(lengths, s) - 1, 0), len(points) - 2)
        seg = lengths[i + 1] - lengths[i] or 1.0
        t = (s - lengths[i]) / seg
        (x0, y0), (x1, y1) = points[i], points[i + 1]
        return (x0 + (x1 - x0) * t, y0 + (y1 - y0) * t)

    return f, total


def circumradius(a: Point, b: Point, c: Point) -> float:
    """Radius of the circle through three points (huge when they are collinear)."""
    ab = math.hypot(b[0] - a[0], b[1] - a[1])
    bc = math.hypot(c[0] - b[0], c[1] - b[1])
    ca = math.hypot(a[0] - c[0], a[1] - c[1])
    area2 = abs((b[0] - a[0]) * (c[1] - a[1]) - (c[0] - a[0]) * (b[1] - a[1]))
    return (ab * bc * ca) / (2 * area2) if area2 > 1e-9 else 1e9


def outline(
    pts: list[Point], width: Width, closed: bool, u0: float = 0.0, u1: float = 1.0
) -> str:
    """The filled outline of a variable-width stroke along `pts`. The width function
    sees the stroke's global parameter (u0..u1) and the tangent angle at each sample."""
    if closed:
        pts = pts[:-1]
    n = len(pts)
    left: list[Point] = []
    right: list[Point] = []
    for i, (x, y) in enumerate(pts):
        if closed:
            (ax, ay), (bx, by) = pts[(i - 1) % n], pts[(i + 1) % n]
        else:
            (ax, ay), (bx, by) = pts[max(i - 1, 0)], pts[min(i + 1, n - 1)]
        tx, ty = bx - ax, by - ay
        norm = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / norm, tx / norm
        u = u0 + (u1 - u0) * i / (n - 1)
        w = width(u, math.atan2(ty, tx)) / 2
        # never offset past the centre of curvature: the offset curve would fold back on
        # itself and punch a hole where a pen would simply pool
        w = min(w, 0.85 * circumradius((ax, ay), (x, y), (bx, by)))
        left.append((x + nx * w, y + ny * w))
        right.append((x - nx * w, y - ny * w))
    if closed:
        return spline(left, True) + spline(right[::-1], True)
    return spline(left + right[::-1], True)


def brush(
    base: float,
    *,
    nib_deg: float = 32.0,
    contrast: float = 0.55,
    entry: float = 0.06,
    exit: float = 0.10,
    swell: float = 0.0,
    swell_at: float = 0.5,
    floor: float = 0.10,
) -> Width:
    """A flat brush held at `nib_deg`: full width across the nib, `1 - contrast` of it
    along the nib; pressed harder around `swell_at`; lifted in over `entry` and out over
    `exit` of the stroke (a lift of 0 keeps the end blunt)."""
    nib = math.radians(nib_deg)

    def width(u: float, ang: float) -> float:
        angular = 1 - contrast * (1 - abs(math.sin(ang - nib)))
        pressure = 1 + swell * math.exp(-((u - swell_at) ** 2) / 0.08)
        lift = 1.0
        if entry:
            lift *= floor + (1 - floor) * smoothstep(u / entry)
        if exit:
            lift *= floor + (1 - floor) * smoothstep((1 - u) / exit)
        return max(base * angular * pressure * lift, 0.5)

    return width


def enso_brush(base: float, *, nib_deg: float = 15.0, contrast: float = 0.2) -> Width:
    """The one-breath circle: down heavy at the start, thinning to a dry tail."""
    nib = math.radians(nib_deg)

    def width(u: float, ang: float) -> float:
        angular = 1 - contrast * (1 - abs(math.sin(ang - nib)))
        body = 1.0 + 0.12 * smoothstep(u / 0.2) - 0.92 * smoothstep((u - 0.45) / 0.55)
        start = 0.6 + 0.4 * smoothstep(u / 0.04)
        return max(base * angular * body * start, 0.6)

    return width


# ----------------------------------------------------------------------------- curves


def ellipse(cx: float, cy: float, rx: float, ry: float, rot_deg: float = 0.0) -> Curve:
    r = math.radians(rot_deg)
    cr, sr = math.cos(r), math.sin(r)

    def f(u: float) -> Point:
        t = math.tau * u
        x, y = rx * math.cos(t), ry * math.sin(t)
        return (cx + x * cr - y * sr, cy + x * sr + y * cr)

    return f


def circle(cx: float, cy: float, r: float) -> Curve:
    return ellipse(cx, cy, r, r)


def arc(
    cx: float, cy: float, r: float, a0: float, a1: float, n: int = 24
) -> list[Point]:
    """Points along a circular arc from angle a0 to a1 (degrees, SVG orientation)."""
    return [
        (
            cx + r * math.cos(math.radians(a0 + (a1 - a0) * i / n)),
            cy + r * math.sin(math.radians(a0 + (a1 - a0) * i / n)),
        )
        for i in range(n + 1)
    ]


def placed(
    points: list[Point],
    *,
    scale: float,
    rot_deg: float,
    cx: float = C,
    cy: float = C,
    flip_y: bool = False,
) -> list[Point]:
    """Scale, rotate and centre a point list on the canvas (flip_y for y-up drawings)."""
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    mx, my = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
    r = math.radians(rot_deg)
    cr, sr = math.cos(r), math.sin(r)
    out = []
    for x, y in points:
        x, y = (x - mx) * scale, (y - my) * scale * (-1 if flip_y else 1)
        out.append((cx + x * cr - y * sr, cy + x * sr + y * cr))
    return out


def trefoil(scale: float, rot_deg: float) -> Curve:
    """The simplest knot: one line, three lobes, six alternating crossings."""
    r = math.radians(rot_deg)
    cr, sr = math.cos(r), math.sin(r)

    def f(u: float) -> Point:
        t = math.tau * u
        x = (math.sin(t) + 2 * math.sin(2 * t)) * scale
        y = (math.cos(t) - 2 * math.cos(2 * t)) * scale
        return (C + x * cr - y * sr, C + x * sr + y * cr)

    return f


# ---------------------------------------------------------------------------- strokes


@dataclass
class Shape:
    """One filled SVG path (plus, for a woven stroke, the mask that carves the gaps)."""

    d: str
    fill: str
    opacity: float = 1.0
    mask: str = ""  # id of a mask this path is drawn through
    defs: list[str] = field(default_factory=list)  # <mask> elements this shape needs

    def svg(self) -> str:
        fill = "currentColor" if self.fill == INK else self.fill
        attrs = [f'd="{self.d}"', f'fill="{fill}"']
        if self.opacity < 1:
            attrs.append(f'opacity="{self.opacity:.2f}"')
        if self.mask:
            attrs.append(f'mask="url(#{self.mask})"')
        return "".join(self.defs) + f"<path {' '.join(attrs)}/>"


def stroke(
    curve: Curve,
    width: Width,
    *,
    fill: str,
    u0: float = 0.0,
    u1: float = 1.0,
    samples: int = 160,
    wobble: Wobble | None = None,
    closed: bool = False,
) -> Shape:
    pts = trace(curve, u0, u1, samples, wobble)
    # the brush sees progress along the drawn stroke, not the curve's own parameter
    return Shape(outline(pts, width, closed), fill)


def crossings(curve: Curve, samples: int = 480) -> list[tuple[float, float]]:
    """Parameter pairs (u_a, u_b) where the curve crosses itself."""
    pts = [curve(i / samples) for i in range(samples + 1)]
    found: list[tuple[float, float]] = []
    for i in range(samples):
        (ax, ay), (bx, by) = pts[i], pts[i + 1]
        for j in range(i + 2, samples):
            if i == 0 and j == samples - 1:
                continue  # the closing segment is adjacent to the first
            (cx, cy), (dx, dy) = pts[j], pts[j + 1]
            den = (bx - ax) * (dy - cy) - (by - ay) * (dx - cx)
            if abs(den) < 1e-12:
                continue
            s = ((cx - ax) * (dy - cy) - (cy - ay) * (dx - cx)) / den
            t = ((cx - ax) * (by - ay) - (cy - ay) * (bx - ax)) / den
            if 0 <= s < 1 and 0 <= t < 1:
                found.append(((i + s) / samples, (j + t) / samples))
    return found


def woven(
    curve: Curve,
    width: Width,
    *,
    fill: str,
    mask_id: str,
    base_width: float,
    samples: int = 480,
    gap: float | None = None,
    reach: float | None = None,
) -> Shape:
    """A closed stroke that crosses itself, drawn as rope: at each crossing the strand
    visited later in an alternating walk passes *over* — the under strand is carved
    away around it by a mask, so the weave holds on any background."""
    gap = gap if gap is not None else base_width * 0.42
    reach = reach if reach is not None else base_width * 2.1
    # arc length, to turn a reach in pixels into a span in u
    pts = [curve(i / samples) for i in range(samples + 1)]
    total = sum(
        math.hypot(b[0] - a[0], b[1] - a[1]) for a, b in zip(pts, pts[1:], strict=False)
    )
    span = reach / total
    visits = sorted(
        (u, k) for k, pair in enumerate(crossings(curve, samples)) for u in pair
    )
    over = [u for n, (u, _k) in enumerate(visits) if n % 2 == 0]
    halos: list[str] = []
    tops: list[str] = []
    for u in over:
        seg = trace(curve, u - span, u + span, 40)
        halos.append(
            outline(
                seg, lambda uu, ang: width(uu, ang) + 2 * gap, False, u - span, u + span
            )
        )
        tops.append(outline(seg, width, False, u - span, u + span))
    body = outline(trace(curve, 0.0, 1.0, samples), width, True)
    mask = (
        f'<mask id="{mask_id}" maskUnits="userSpaceOnUse" x="0" y="0" width="{SIZE:.0f}" height="{SIZE:.0f}">'
        f'<rect width="{SIZE:.0f}" height="{SIZE:.0f}" fill="#fff"/>'
        + "".join(f'<path d="{h}" fill="#000"/>' for h in halos)
        + "</mask>"
    )
    return Shape(body + "".join(tops), fill, mask=mask_id, defs=[mask])


def arrowhead(
    curve: Curve, *, fill: str, length: float = 22.0, half: float = 11.0, u: float = 1.0
) -> Shape:
    """A filled chevron whose tip continues the stroke's direction at `u`."""
    px, py = curve(u)
    tx, ty = tangent(curve, u)
    nx, ny = -ty, tx
    tip = (px + tx * length, py + ty * length)
    left = (px - tx * length * 0.3 + nx * half, py - ty * length * 0.3 + ny * half)
    right = (px - tx * length * 0.3 - nx * half, py - ty * length * 0.3 - ny * half)
    return Shape(f"M{fmt(left)}L{fmt(tip)}L{fmt(right)}Z", fill)


# ---------------------------------------------------------------------------- options


@dataclass
class Option:
    slug: str
    name: str
    character: str  # the personality, in a word or two
    concept: str  # one sentence
    meaning: list[str]
    made_of: str
    shapes: list[Shape]


def option_loop_word() -> Option:
    """The name, written in one line, is itself the loops."""
    keys: list[Point] = [
        # l — a tall loop
        (-0.30, 0.05),
        (0.15, 0.50),
        (0.55, 1.40),
        (0.70, 2.25),
        (0.50, 2.48),
        (0.27, 2.05),
        (0.25, 1.05),
        (0.42, 0.25),
        (0.82, 0.02),
        (1.18, 0.35),
    ]
    for cx in (1.72, 2.68):  # o o — two inner loops, each closed with a tiny top curl
        keys += [
            (cx + 0.05, 0.92),
            (cx - 0.12, 1.06),
            (cx - 0.44, 0.72),
            (cx - 0.34, 0.16),
            (cx + 0.08, 0.00),
            (cx + 0.44, 0.42),
            (cx + 0.34, 0.92),
            (cx + 0.12, 1.04),
            (cx + 0.52, 1.00),
        ]
    keys += [
        # p — a stem, a descender loop, a bowl
        (3.30, 1.02),
        (3.46, 0.60),
        (3.46, -0.60),
        (3.38, -1.24),
        (3.60, -1.18),
        (3.56, -0.40),
        (3.52, 0.55),
        (3.64, 1.04),
        (4.06, 1.00),
        (4.24, 0.55),
        (4.00, 0.08),
        (3.58, 0.10),
        (3.98, 0.00),
        (4.34, 0.32),
    ]
    points = placed(
        catmull_points(keys, 18), scale=46, rot_deg=-4, flip_y=True, cy=C + 4
    )
    curve, _ = by_arc_length(points)
    pen = brush(9.5, nib_deg=28, contrast=0.45, entry=0.03, exit=0.05, floor=0.18)
    shapes = [stroke(curve, pen, fill=INK, samples=720)]
    return Option(
        "option-1-loop",
        "loop",
        "wit",
        "The name, written in one line, is itself the loops: the l's tall outer loop, the two inner loops of the o's, the p's loop below the line.",
        [
            "One continuous brush stroke — the pen never lifts between the four letters, so the word is one loop made of loops.",
            "Outer and inner are the letters' own: the l reaches above, the p reaches below, the two o's sit inside.",
            "It is the wordmark and the mark at once; at favicon size it reads as a knotted line.",
        ],
        "a Catmull-Rom spline through 45 hand-placed points, arc-length parameterised, drawn with a flat brush at 28°",
        shapes,
    )


def option_knot() -> Option:
    curve = trefoil(31.0, 180)
    pen = brush(11.5, nib_deg=40, contrast=0.32, entry=0.0, exit=0.0)
    shapes = [
        woven(
            curve,
            pen,
            fill=INK,
            mask_id="option-2-knot-weave",
            base_width=11.5,
            samples=420,
            gap=2.2,
        )
    ]
    return Option(
        "option-2-knot",
        "Knot",
        "strength",
        "One line, three loops, six crossings — a trefoil knot: nothing holds a loop like another loop.",
        [
            "Every loop passes over one neighbour and under the next; pull any one and the others hold it.",
            "The centre is the inner loop no line draws — the space the three keep between them.",
            "Drawn as rope, not as a diagram: the weave is what gives it weight.",
        ],
        "the trefoil curve (sin t + 2 sin 2t, cos t − 2 cos 2t) as one brush stroke; the six crossings found numerically and woven with a mask",
        shapes,
    )


def option_flick() -> Option:
    """A stroke that loops back on itself and still moves forward."""
    raw: list[Point] = []
    n = 700
    t0, t1 = -2.6, 2 * math.tau + 1.9
    for i in range(n + 1):
        t = t0 + (t1 - t0) * i / n
        b = 2.15 - 0.32 * (t / math.tau)
        raw.append((t - b * math.sin(t), b * math.cos(t)))
    points = placed(raw, scale=14.0, rot_deg=-24, flip_y=True, cx=C - 2, cy=C + 4)
    curve, _ = by_arc_length(points)
    pen = brush(
        9.2,
        nib_deg=25,
        contrast=0.4,
        entry=0.14,
        exit=0.0,
        swell=0.22,
        swell_at=0.5,
        floor=0.06,
    )
    shapes = [
        stroke(curve, pen, fill=INK, samples=600, u1=0.94),
        arrowhead(curve, fill=INK, length=30, half=14, u=0.94),
    ]
    return Option(
        "option-3-flick",
        "Flick",
        "momentum",
        "A stroke that loops back on itself twice and still moves forward: iteration with momentum.",
        [
            "Each loop is a pass round the cycle; each is smaller than the last, because the work converges.",
            "The outer sweep carries the inner loops — the line that goes round is the line that goes on.",
            "It ends in an arrow, not a full stop: the loop is a direction.",
        ],
        "a prolate cycloid (x = t − b·sin t, y = b·cos t) whose loop size b shrinks along t, swept at −24°, a brush that presses hardest through the loops, and a chevron on the tangent",
        shapes,
    )


def option_clip() -> Option:
    """One wire, an inner loop inside an outer loop: the thing that holds the work."""
    pts: list[Point] = [(16, -18), (16, 38)]
    pts += arc(0, 40, 16, 0, 180)  # inner bottom
    pts += [(-16, 38), (-16, -44)]
    pts += arc(9, -46, 25, 180, 360)  # top, over to the outer right
    pts += [(34, -44), (34, 44)]
    pts += arc(0, 46, 34, 0, 180)  # outer bottom
    pts += [(-34, 44), (-34, -4)]
    points = placed(catmull_points(pts, 4), scale=1.32, rot_deg=-22, cx=C + 2)
    curve, _ = by_arc_length(points)
    pen = brush(8.6, nib_deg=30, contrast=0.38, entry=0.04, exit=0.04)
    shapes = [stroke(curve, pen, fill=INK, samples=560)]
    return Option(
        "option-4-clip",
        "Clip",
        "utility, with a wink",
        "A paperclip: one wire bent into an inner loop inside an outer loop — the thing that holds the work together.",
        [
            "Everyone already knows what it does: it keeps the pages of one thing from coming apart.",
            "Inner and outer are literal — the small loop sits inside the large one, and the same wire makes both.",
            "Tilted like a clip left on a desk; drawn with a brush so it is an object, not an icon.",
        ],
        "eight legs and arcs in the proportions of a wire clip, smoothed, tilted −22°, one brush stroke",
        shapes,
    )


def option_enso() -> Option:
    rng = random.Random(398_5)
    shapes = []
    for r, fill, start, base in (
        (100, INK, 118, 16.0),
        (65, DUSK, 250, 13.0),
        (33, CLAY, 20, 9.5),
    ):
        u0 = start / 360
        shapes.append(
            stroke(
                circle(C, C, r),
                enso_brush(base),
                fill=fill,
                u0=u0,
                u1=u0 + 0.875,
                samples=200,
                wobble=Wobble(rng, 0.6),
            )
        )
    return Option(
        "option-5-enso",
        "Ensō",
        "calm",
        "Three brush circles, each left open where the hand lifted: the outer loop, the inner loop, and the one between — none of them closed until the work is.",
        [
            "One breath per circle, heavy where it starts and dry where it ends; the gap is the loop still running.",
            "Nested, not concentric in spirit: each opens at its own angle, each is its own colour.",
            "The quiet option — a mark that reads at any size and asks nothing of the eye.",
        ],
        "three arcs of 315°, each a brush that starts heavy and thins to a dry tail; ink, dusk and clay",
        shapes,
    )


OPTIONS: list[Callable[[], Option]] = [
    option_loop_word,
    option_knot,
    option_flick,
    option_clip,
    option_enso,
]


# ------------------------------------------------------------------------------- svg


def svg_body(opt: Option) -> str:
    return "\n".join(s.svg() for s in opt.shapes)


def svg_file(opt: Option) -> str:
    """The standalone file. The ink is `currentColor`, set once on the root and swapped
    for the dark-scheme ink by the one media rule; accents are mid-toned enough for
    either ground."""
    title = f"the-loop — {opt.name}"
    style = f"@media (prefers-color-scheme:dark){{svg{{color:{INK_ON_SLATE}}}}}"
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}" '
        f'color="{INK}" role="img" aria-labelledby="{opt.slug}-title {opt.slug}-desc">\n'
        f'<title id="{opt.slug}-title">{title}</title>\n'
        f'<desc id="{opt.slug}-desc">{opt.concept} Generated by docs/specs/issue-398/design/generate.py.</desc>\n'
        f"<style>{style}</style>\n"
        f"{svg_body(opt)}\n"
        "</svg>\n"
    )


def svg_symbol(opt: Option) -> str:
    return f'<symbol id="{opt.slug}" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}">{svg_body(opt)}</symbol>'


def svg_use(opt: Option, px: int) -> str:
    return f'<svg width="{px}" height="{px}" aria-hidden="true"><use href="#{opt.slug}"/></svg>'


# --------------------------------------------------------------------------- gallery


GALLERY_CSS = (
    """
:root{--paper:@paper;--slate:@slate;--ink:@ink;--ink-slate:@ink_slate;--rule:#d9d2c4;--muted:#7a736a}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;padding:32px 16px 64px}
main{max-width:1080px;margin:0 auto}
h1{font-size:26px;margin:0 0 6px;letter-spacing:-.01em}
h2{font-size:20px;margin:0}
p{margin:0 0 8px}
.lede{color:var(--muted);max-width:70ch;margin-bottom:24px}
.palette{display:flex;flex-wrap:wrap;gap:10px;margin:0 0 36px}
.swatch{display:flex;align-items:center;gap:8px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.swatch i{width:22px;height:22px;border-radius:50%;border:1px solid var(--rule);display:inline-block}
.option{border-top:1px solid var(--rule);padding:28px 0 36px}
.option header{display:flex;flex-wrap:wrap;align-items:baseline;gap:6px 14px;margin-bottom:6px}
.option .n{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.option .c{color:var(--muted);font-style:italic}
.concept{font-size:17px;max-width:70ch;margin-bottom:16px}
.boards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin-bottom:16px}
.board{border-radius:14px;padding:18px;display:flex;align-items:center;justify-content:center;min-height:256px;border:1px solid var(--rule)}
.board.paper{background:var(--paper);color:var(--ink)}
.board.slate{background:var(--slate);border-color:#3a3e45;color:var(--ink-slate)}
.defs{position:absolute;width:0;height:0;overflow:hidden}
.board.sizes{flex-direction:row;gap:22px;align-items:flex-end;flex-wrap:wrap}
.board.sizes figure{margin:0;display:flex;flex-direction:column;align-items:center;gap:6px}
.board.sizes figcaption{font:11px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.lockup{display:flex;align-items:center;gap:12px;font:600 26px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:-.02em;margin:0 0 18px;color:var(--ink)}
@media (prefers-color-scheme:dark){.lockup{color:var(--ink-slate)}}
.meaning{margin:0 0 10px;padding-left:20px;max-width:80ch}
.meaning li{margin:0 0 4px}
.made{color:var(--muted);font-size:13px;max-width:80ch}
.made code{font:12px ui-monospace,SFMono-Regular,Menlo,monospace}
footer{border-top:1px solid var(--rule);padding-top:18px;color:var(--muted);font-size:13px}
footer code{font:12px ui-monospace,SFMono-Regular,Menlo,monospace}
@media (prefers-color-scheme:dark){
  body{background:var(--slate);color:var(--ink-slate)}
  :root{--rule:#3a3e45;--muted:#a49d92}
  .board.paper{background:var(--paper);color:var(--ink)}
}
""".replace("@paper", PAPER)
    .replace("@slate", SLATE)
    .replace("@ink_slate", INK_ON_SLATE)
    .replace("@ink", INK)
)


def gallery(options: list[Option]) -> str:
    swatches = "".join(
        f'<span class="swatch"><i style="background:{hexv}"></i>{name} {hexv}</span>'
        for name, hexv in (
            ("ink", INK),
            ("sage", SAGE),
            ("dusk", DUSK),
            ("clay", CLAY),
            ("ochre", OCHRE),
            ("mauve", MAUVE),
            ("paper", PAPER),
            ("slate", SLATE),
        )
    )
    cards = []
    for i, opt in enumerate(options, 1):
        sizes = "".join(
            f"<figure>{svg_use(opt, px)}<figcaption>{px}px</figcaption></figure>"
            for px in (96, 48, 24, 16)
        )
        meaning = "".join(f"<li>{m}</li>" for m in opt.meaning)
        cards.append(
            f'<section class="option" id="{opt.slug}">\n'
            f'<header><span class="n">option {i} · <code>{opt.slug}.svg</code></span><h2>{opt.name}</h2><span class="c">{opt.character}</span></header>\n'
            f'<p class="concept">{opt.concept}</p>\n'
            f'<div class="boards">\n'
            f'<div class="board paper">{svg_use(opt, 220)}</div>\n'
            f'<div class="board slate">{svg_use(opt, 220)}</div>\n'
            f'<div class="board paper sizes">{sizes}</div>\n'
            f"</div>\n"
            f'<div class="lockup">{svg_use(opt, 40)}<span>the-loop</span></div>\n'
            f'<ul class="meaning">{meaning}</ul>\n'
            f'<p class="made">Drawn as: {opt.made_of}.</p>\n'
            f"</section>"
        )
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>the-loop — logo options, round 2 (issue-398)</title>\n"
        f"<style>{GALLERY_CSS}</style>\n</head>\n<body>\n"
        f'<svg class="defs" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">{"".join(svg_symbol(o) for o in options)}</svg>\n'
        "<main>\n"
        "<h1>the-loop — logo options, round 2</h1>\n"
        '<p class="lede">Round 1 drew five loop <em>structures</em> with a wobbling, over-drawn hand; the review asked for '
        "character and less stress on the hand-drawn part. Round 2 keeps the hand — a flat brush held at an angle, pressed "
        "and lifted, never shaky — and gives each mark a <em>personality</em>: wit, strength, momentum, utility, calm. "
        "Each is one standalone SVG in one muted palette, shown on paper, on slate, at four sizes down to a favicon, and "
        "beside the name. Pick one on the ticket; feedback becomes a parameter change and a re-run.</p>\n"
        f'<div class="palette">{swatches}</div>\n' + "\n".join(cards) + "\n<footer>\n"
        "<p>Source: <code>docs/specs/issue-398/design/generate.py</code> — stdlib Python, no dependencies. "
        "<code>python3 generate.py</code> rewrites every file here; <code>python3 generate.py --check</code> "
        "verifies the files on disk are exactly what the script makes, well-formed and self-contained. "
        "Round 1 is in the git history of this folder.</p>\n"
        "</footer>\n</main>\n</body>\n</html>\n"
    )


# ------------------------------------------------------------------------------ main


def render() -> dict[str, str]:
    options = [make() for make in OPTIONS]
    files = {f"{opt.slug}.svg": svg_file(opt) for opt in options}
    files["logo-options.html"] = gallery(options)
    return files


FORBIDDEN = ("<script", "<foreignObject", "<image", "<iframe", "@import", "src=")
EXTERNAL_REF = re.compile(
    r'href="(?!#)|url\((?!#)'
)  # a fragment is the file's own <use> or <mask>


def check(files: dict[str, str]) -> list[str]:
    problems: list[str] = []
    for name, content in files.items():
        path = HERE / name
        if not path.exists():
            problems.append(f"{name}: missing")
            continue
        if path.read_text(encoding="utf-8") != content:
            problems.append(
                f"{name}: differs from what generate.py produces (re-run it)"
            )
        if name.endswith(".svg"):
            try:
                root = ET.fromstring(content)
            except ET.ParseError as e:
                problems.append(f"{name}: not well-formed XML ({e})")
                continue
            ns = "{http://www.w3.org/2000/svg}"
            if root.find(f"{ns}title") is None or root.find(f"{ns}desc") is None:
                problems.append(f"{name}: missing <title> or <desc>")
            if len(content.encode()) > 64_000:
                problems.append(f"{name}: over 64 kB")
        for token in FORBIDDEN:
            if token in content:
                problems.append(f"{name}: contains {token!r}")
        if EXTERNAL_REF.search(content):
            problems.append(f"{name}: has an href or url() that is not a fragment")
    if render() != files:
        problems.append("generate.py is not deterministic")
    return problems


def main(argv: list[str]) -> int:
    files = render()
    if "--check" in argv:
        problems = check(files)
        for p in problems:
            print(f"FAIL {p}")
        if not problems:
            print(f"ok — {len(files)} files match, well-formed, self-contained, titled")
        return 1 if problems else 0
    for name, content in files.items():
        (HERE / name).write_text(content, encoding="utf-8")
        print(f"wrote {name} ({len(content.encode()) / 1000:.1f} kB)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
