#!/usr/bin/env python3
# ruff: noqa: E501 — the strings are prose and CSS; wrapping them would not help a reader
"""the-loop logo (issue-398): the Ensō, in colourways, from one generator.

Usage:

    python3 generate.py            write the SVGs and the gallery next to this file, and
                                   the adopted mark's brand assets under docs/ and ui/
    python3 generate.py --check    verify the files on disk are exactly what this script
                                   makes, well-formed, self-contained and titled

Standard library only. The mark is three brush circles, each left open where the hand
lifted — outer, inner, and the one between. Each circle is one *stroke*: a centreline
outlined by a brush that comes down heavy, presses, and thins to a dry tail, emitted as
a filled path. Nothing depends on fonts or filters, so the files render the same in a
browser, a README, a favicon and an image tool. Change a parameter, re-run, and every
file is regenerated byte-for-byte.

Round 1 (git history) drew five loop structures with a wobbling hand; round 2 (git
history) drew five marks with a character each; the owner chose the Ensō and asked for
colour and gradient options. Round 3 is that: one mark, several colourways — flat
palettes, a gradient that travels along each stroke, an ink-to-accent "running dry",
and a linear sweep across the mark.
"""

from __future__ import annotations

import math
import random
import re
import sys
import xml.etree.ElementTree as ET
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIZE = 256.0
C = SIZE / 2

# The palette: one warm ink, five muted accents, paper and slate for the two grounds.
INK = "#3f3a33"
INK_ON_SLATE = "#e9e3d7"
PAPER = "#f5f0e6"
SLATE = "#22252a"
SAGE = "#8a9c84"
DUSK = "#7f93a5"
CLAY = "#c48a6c"
OCHRE = "#c7a86b"
MAUVE = "#9d8a9f"
NAMES = {
    INK: "ink",
    SAGE: "sage",
    DUSK: "dusk",
    CLAY: "clay",
    OCHRE: "ochre",
    MAUVE: "mauve",
}

Point = tuple[float, float]
Curve = Callable[[float], Point]
Width = Callable[[float, float], float]  # (u along the stroke, tangent angle) → width


# --------------------------------------------------------------------------- geometry


def fmt(p: Point) -> str:
    return f"{p[0]:.1f} {p[1]:.1f}"


def smoothstep(x: float) -> float:
    x = min(1.0, max(0.0, x))
    return x * x * (3 - 2 * x)


class Wobble:
    """Seeded sideways noise: a few integer harmonics of the stroke's own period — a
    hair of warmth, never a tremor."""

    def __init__(self, rng: random.Random, amp: float, harmonics=(2, 3, 5)) -> None:
        self.terms = [
            (amp / (i + 1), h, rng.uniform(0, math.tau))
            for i, h in enumerate(harmonics)
        ]

    def __call__(self, u: float) -> float:
        return sum(a * math.sin(math.tau * h * u + p) for a, h, p in self.terms)


def tangent(curve: Curve, u: float, du: float = 1e-3) -> tuple[float, float]:
    ax, ay = curve(u - du)
    bx, by = curve(u + du)
    tx, ty = bx - ax, by - ay
    norm = math.hypot(tx, ty) or 1.0
    return tx / norm, ty / norm


def trace(
    curve: Curve, u0: float, u1: float, n: int, wobble: Wobble | None = None
) -> list[Point]:
    """Sample `curve` on [u0, u1], pushing each sample along its normal by the wobble."""
    pts: list[Point] = []
    for i in range(n + 1):
        u = u0 + (u1 - u0) * i / n
        x, y = curve(u)
        tx, ty = tangent(curve, u)
        off = wobble(u) if wobble else 0.0
        pts.append((x - ty * off, y + tx * off))
    return pts


def spline(pts: list[Point], closed: bool) -> str:
    """Catmull-Rom through the points, emitted as cubic Béziers."""
    n = len(pts)

    def at(i: int) -> Point:
        return pts[i % n] if closed else pts[min(max(i, 0), n - 1)]

    out = [f"M{fmt(pts[0])}"]
    for i in range(n if closed else n - 1):
        p0, p1, p2, p3 = at(i - 1), at(i), at(i + 1), at(i + 2)
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        out.append(f"C{fmt(c1)} {fmt(c2)} {fmt(p2)}")
    out.append("Z")
    return "".join(out)


def circumradius(a: Point, b: Point, c: Point) -> float:
    """Radius of the circle through three points (huge when they are collinear)."""
    ab = math.hypot(b[0] - a[0], b[1] - a[1])
    bc = math.hypot(c[0] - b[0], c[1] - b[1])
    ca = math.hypot(a[0] - c[0], a[1] - c[1])
    area2 = abs((b[0] - a[0]) * (c[1] - a[1]) - (c[0] - a[0]) * (b[1] - a[1]))
    return (ab * bc * ca) / (2 * area2) if area2 > 1e-9 else 1e9


def edges(pts: list[Point], width: Width) -> tuple[list[Point], list[Point]]:
    """The left and right edges of a variable-width open stroke along `pts`. The width
    function sees the stroke's progress (0..1) and the tangent angle at each sample."""
    n = len(pts)
    left: list[Point] = []
    right: list[Point] = []
    for i, (x, y) in enumerate(pts):
        (ax, ay), (bx, by) = pts[max(i - 1, 0)], pts[min(i + 1, n - 1)]
        tx, ty = bx - ax, by - ay
        norm = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / norm, tx / norm
        w = width(i / (n - 1), math.atan2(ty, tx)) / 2
        # never offset past the centre of curvature: the offset curve would fold back on
        # itself and punch a hole where a pen would simply pool
        w = min(w, 0.85 * circumradius((ax, ay), (x, y), (bx, by)))
        left.append((x + nx * w, y + ny * w))
        right.append((x - nx * w, y - ny * w))
    return left, right


def outline(pts: list[Point], width: Width) -> str:
    """The filled outline of a whole stroke."""
    left, right = edges(pts, width)
    return spline(left + right[::-1], True)


def segment(pts: list[Point], i0: float, i1: float) -> str:
    """The cubic Béziers of the open Catmull-Rom curve through `pts` from index i0 to
    i1 — the same segments `spline` would emit for the whole list, so a piece cut
    here abuts its neighbour on an identical curve."""
    n = len(pts)

    def at(i: int) -> Point:
        return pts[min(max(i, 0), n - 1)]

    out = []
    for i in range(int(i0), int(i1)):
        p0, p1, p2, p3 = at(i - 1), at(i), at(i + 1), at(i + 2)
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        out.append(f"C{fmt(c1)} {fmt(c2)} {fmt(p2)}")
    return "".join(out)


def piece(left: list[Point], right: list[Point], i0: int, i1: int) -> str:
    """One piece of a stroke: along the left edge from i0 to i1 on the stroke's own
    curve, straight across, back along the right edge, straight across again."""
    n = len(left)
    rev = right[::-1]
    return (
        f"M{fmt(left[i0])}"
        + segment(left, i0, i1)
        + f"L{fmt(right[i1])}"
        + segment(rev, n - 1 - i1, n - 1 - i0)
        + "Z"
    )


def enso_brush(base: float, *, nib_deg: float = 15.0, contrast: float = 0.2) -> Width:
    """The one-breath circle: down heavy at the start, thinning to a dry tail."""
    nib = math.radians(nib_deg)

    def width(u: float, ang: float) -> float:
        angular = 1 - contrast * (1 - abs(math.sin(ang - nib)))
        body = 1.0 + 0.12 * smoothstep(u / 0.2) - 0.92 * smoothstep((u - 0.45) / 0.55)
        start = 0.6 + 0.4 * smoothstep(u / 0.04)
        return max(base * angular * body * start, 0.6)

    return width


def circle(cx: float, cy: float, r: float) -> Curve:
    def f(u: float) -> Point:
        t = math.tau * u
        return (cx + r * math.cos(t), cy + r * math.sin(t))

    return f


# ------------------------------------------------------------------------------ colour


def _srgb_to_linear(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def _linear_to_srgb(c: float) -> float:
    c = min(1.0, max(0.0, c))
    return 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055


def to_oklab(hexv: str) -> tuple[float, float, float]:
    r, g, b = (_srgb_to_linear(int(hexv[i : i + 2], 16) / 255) for i in (1, 3, 5))
    l_ = (0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b) ** (1 / 3)
    m_ = (0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b) ** (1 / 3)
    s_ = (0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b) ** (1 / 3)
    return (
        0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
        1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
        0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_,
    )


def from_oklab(lab: tuple[float, float, float]) -> str:
    ll, a, b = lab
    l_ = (ll + 0.3963377774 * a + 0.2158037573 * b) ** 3
    m_ = (ll - 0.1055613458 * a - 0.0638541728 * b) ** 3
    s_ = (ll - 0.0894841775 * a - 1.2914855480 * b) ** 3
    r = 4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_
    g = -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_
    bb = -0.0041960863 * l_ - 0.7034186147 * m_ + 1.7076147010 * s_
    return "#" + "".join(f"{round(_linear_to_srgb(c) * 255):02x}" for c in (r, g, bb))


def mix(c0: str, c1: str, t: float) -> str:
    """Perceptual (OKLab) blend of two colours; t=0 is c0, t=1 is c1."""
    a, b = to_oklab(c0), to_oklab(c1)
    return from_oklab(tuple(a[i] + (b[i] - a[i]) * t for i in range(3)))  # type: ignore[arg-type]


# ---------------------------------------------------------------------------- the mark


@dataclass
class Shape:
    """One filled SVG path, with any <defs> it needs and a dark-scheme fill if its
    light one is not legible on slate."""

    d: str
    fill: str
    cls: str = ""
    dark: str = ""
    defs: list[str] = field(default_factory=list)

    def svg(self) -> str:
        attrs = [f'd="{self.d}"', f'fill="{self.fill}"']
        if self.cls:
            attrs.insert(0, f'class="{self.cls}"')
        return "".join(self.defs) + f"<path {' '.join(attrs)}/>"


# radius, angle the brush lands at, base width — the round-2 Ensō, unchanged
RINGS = ((100.0, 118.0, 16.0), (65.0, 250.0, 13.0), (33.0, 20.0, 9.5))
ARC = 0.875  # 315° of each circle; the gap is where the hand lifted
CHUNKS = 20  # pieces per stroke when the colour travels along it
SEED = 398_5

Paint = (
    str | tuple[str, str]
)  # a flat colour ("ink" allowed), or (start, end) along the stroke


@dataclass
class Variant:
    slug: str
    name: str
    note: str
    rings: tuple[Paint, Paint, Paint]  # outer, middle, inner
    sweep: tuple[str, str] | None = None  # one linear gradient across the whole mark

    @property
    def gradient(self) -> bool:
        return self.sweep is not None or any(isinstance(p, tuple) for p in self.rings)


def ring_curves() -> list[tuple[Curve, Wobble, float, float]]:
    """The three strokes' geometry, identical for every colourway."""
    rng = random.Random(SEED)
    out = []
    for r, start, base in RINGS:
        out.append((circle(C, C, r), Wobble(rng, 0.6), start / 360, base))
    return out


SAMPLES = 200  # per stroke


def flat_ring(curve: Curve, wobble: Wobble, u0: float, base: float, fill: str) -> Shape:
    pts = trace(curve, u0, u0 + ARC, SAMPLES, wobble)
    return Shape(outline(pts, enso_brush(base)), fill)


def travelling_ring(
    curve: Curve,
    wobble: Wobble,
    u0: float,
    base: float,
    c0: str,
    c1: str,
    ring: int,
    slug: str,
) -> list[Shape]:
    """The stroke in CHUNKS pieces, each a shade further from c0 toward c1 — the colour
    travels with the brush. The pieces are cut from ONE outline, so their edges abut
    exactly; each overlaps the next by a sample to hide the seam. A piece whose light
    colour starts from the ink gets a dark-scheme colour too, from the slate ink,
    through a class the stylesheet maps."""
    left, right = edges(trace(curve, u0, u0 + ARC, SAMPLES, wobble), enso_brush(base))
    shapes: list[Shape] = []
    per = SAMPLES // CHUNKS
    for k in range(CHUNKS):
        i0 = k * per
        i1 = SAMPLES if k == CHUNKS - 1 else (k + 1) * per + 1  # +1: overlap the seam
        d = piece(left, right, i0, i1)
        t = (k + 0.5) / CHUNKS
        light = mix(INK if c0 == "ink" else c0, INK if c1 == "ink" else c1, t)
        dark = ""
        if "ink" in (c0, c1):
            dark = mix(
                INK_ON_SLATE if c0 == "ink" else c0,
                INK_ON_SLATE if c1 == "ink" else c1,
                t,
            )
        shapes.append(
            Shape(d, light, cls=f"{slug}-r{ring}-{k}" if dark else "", dark=dark)
        )
    return shapes


def render_variant(v: Variant) -> list[Shape]:
    shapes: list[Shape] = []
    if v.sweep:
        gid = f"{v.slug}-sweep"
        defs = (
            f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="36" y1="36" x2="220" y2="220">'
            f'<stop offset="0" stop-color="{v.sweep[0]}"/><stop offset="1" stop-color="{v.sweep[1]}"/></linearGradient>'
        )
        for i, (curve, wobble, u0, base) in enumerate(ring_curves()):
            s = flat_ring(curve, wobble, u0, base, f"url(#{gid})")
            if i == 0:
                s.defs.append(defs)
            shapes.append(s)
        return shapes
    for i, ((curve, wobble, u0, base), paint) in enumerate(
        zip(ring_curves(), v.rings, strict=True)
    ):
        if isinstance(paint, tuple):
            shapes += travelling_ring(
                curve, wobble, u0, base, paint[0], paint[1], i, v.slug
            )
        else:
            shapes.append(
                flat_ring(
                    curve, wobble, u0, base, "currentColor" if paint == "ink" else paint
                )
            )
    return shapes


VARIANTS: list[Variant] = [
    Variant(
        "enso-1-ink-dusk-clay",
        "ink · dusk · clay",
        "the round-2 original: ink outside, dusk between, clay at the centre",
        ("ink", DUSK, CLAY),
    ),
    Variant(
        "enso-2-ink",
        "ink",
        "one colour, the purist: three breaths of the same brush; follows the ground's ink",
        ("ink", "ink", "ink"),
    ),
    Variant(
        "enso-3-ink-ink-clay",
        "ink · ink · clay",
        "ink with one warm centre — the ticket at the heart of the loops",
        ("ink", "ink", CLAY),
    ),
    Variant(
        "enso-4-clay-ochre-ink",
        "clay · ochre · ink",
        "warm outside, ink at the centre",
        (CLAY, OCHRE, "ink"),
    ),
    Variant(
        "enso-5-dusk-sage-ink",
        "dusk · sage · ink",
        "cool outside, ink at the centre",
        (DUSK, SAGE, "ink"),
    ),
    Variant(
        "enso-6-sage-ochre-clay",
        "sage · ochre · clay",
        "earth, no ink: every ring a mid-tone that reads on paper and slate alike",
        (SAGE, OCHRE, CLAY),
    ),
    Variant(
        "enso-7-mauve-dusk-clay",
        "mauve · dusk · clay",
        "the quieter trio: mauve outside, dusk between, clay at the centre; no ink",
        (MAUVE, DUSK, CLAY),
    ),
    Variant(
        "enso-8-dusk-to-clay",
        "dusk → clay, along the stroke",
        "each ring cools to warm as the brush travels: dusk where it lands, clay where it lifts",
        ((DUSK, CLAY), (DUSK, CLAY), (DUSK, CLAY)),
    ),
    Variant(
        "enso-9-running-dry",
        "ink → accent, running dry",
        "each ring starts in ink and dries into its own colour — dusk, clay, ochre — as the brush runs out",
        (("ink", DUSK), ("ink", CLAY), ("ink", OCHRE)),
    ),
    Variant(
        "enso-10-sweep",
        "dusk → clay, across the mark",
        "one gradient over the whole mark, top-left to bottom-right, every ring taking its share",
        ("ink", "ink", "ink"),
        sweep=(DUSK, CLAY),
    ),
]


# ------------------------------------------------------------------------------- svg


def svg_body(v: Variant) -> str:
    return "\n".join(s.svg() for s in render_variant(v))


def dark_rules(v: Variant) -> str:
    """Per-piece dark-scheme fills for a travelling ring that starts or ends in ink."""
    return "".join(f".{s.cls}{{fill:{s.dark}}}" for s in render_variant(v) if s.dark)


def svg_file(v: Variant) -> str:
    """The standalone file. Flat ink is `currentColor`, set once on the root and swapped
    for the dark-scheme ink by the one media rule; accents are mid-toned enough for
    either ground; a travelling ring that touches ink carries its own dark fills."""
    title = f"the-loop — Ensō, {v.name}"
    dark = f"svg{{color:{INK_ON_SLATE}}}{dark_rules(v)}"
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}" '
        f'color="{INK}" role="img" aria-labelledby="{v.slug}-title {v.slug}-desc">\n'
        f'<title id="{v.slug}-title">{title}</title>\n'
        f'<desc id="{v.slug}-desc">Three brush circles, each left open where the hand lifted; {v.note}. Generated by docs/specs/issue-398/design/generate.py.</desc>\n'
        f"<style>@media (prefers-color-scheme:dark){{{dark}}}</style>\n"
        f"{svg_body(v)}\n"
        "</svg>\n"
    )


def svg_symbol(v: Variant) -> str:
    return f'<symbol id="{v.slug}" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}">{svg_body(v)}</symbol>'


def svg_use(v: Variant, px: int) -> str:
    return f'<svg width="{px}" height="{px}" aria-hidden="true"><use href="#{v.slug}"/></svg>'


# --------------------------------------------------------------------------- gallery


GALLERY_CSS = (
    """
:root{--paper:@paper;--slate:@slate;--ink:@ink;--ink-slate:@ink_slate;--rule:#d9d2c4;--muted:#7a736a}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;padding:32px 16px 64px}
main{max-width:1080px;margin:0 auto}
h1{font-size:26px;margin:0 0 6px;letter-spacing:-.01em}
h2{font-size:20px;margin:0}
p{margin:0 0 8px}
.lede{color:var(--muted);max-width:70ch;margin-bottom:24px}
.palette{display:flex;flex-wrap:wrap;gap:10px;margin:0 0 36px}
.swatch{display:flex;align-items:center;gap:8px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.swatch i{width:22px;height:22px;border-radius:50%;border:1px solid var(--rule);display:inline-block}
.option{border-top:1px solid var(--rule);padding:28px 0 36px}
.option header{display:flex;flex-wrap:wrap;align-items:baseline;gap:6px 14px;margin-bottom:6px}
.option .n{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.rings{display:inline-flex;gap:6px;vertical-align:middle;margin-left:4px}
.rings i{width:18px;height:18px;border-radius:50%;border:1px solid var(--rule);display:inline-block}
.note{font-size:17px;max-width:70ch;margin-bottom:16px}
.boards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin-bottom:16px}
.board{border-radius:14px;padding:18px;display:flex;align-items:center;justify-content:center;min-height:256px;border:1px solid var(--rule)}
.board.paper{background:var(--paper);color:var(--ink)}
.board.slate{background:var(--slate);border-color:#3a3e45;color:var(--ink-slate)}
.defs{position:absolute;width:0;height:0;overflow:hidden}
.board.sizes{flex-direction:row;gap:22px;align-items:flex-end;flex-wrap:wrap}
.board.sizes figure{margin:0;display:flex;flex-direction:column;align-items:center;gap:6px}
.board.sizes figcaption{font:11px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.lockup{display:flex;align-items:center;gap:12px;font:600 26px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:-.02em;margin:0 0 18px;color:var(--ink)}
@media (prefers-color-scheme:dark){.lockup{color:var(--ink-slate)}}
footer{border-top:1px solid var(--rule);padding-top:18px;color:var(--muted);font-size:13px}
footer code,.made code{font:12px ui-monospace,SFMono-Regular,Menlo,monospace}
.made{color:var(--muted);font-size:13px;max-width:80ch}
@media (prefers-color-scheme:dark){
  body{background:var(--slate);color:var(--ink-slate)}
  :root{--rule:#3a3e45;--muted:#a49d92}
  .board.paper{background:var(--paper);color:var(--ink)}
}
""".replace("@paper", PAPER)
    .replace("@slate", SLATE)
    .replace("@ink_slate", INK_ON_SLATE)
    .replace("@ink", INK)
)


def ring_swatches(v: Variant) -> str:
    def css(paint: Paint) -> str:
        if v.sweep:
            return f"linear-gradient(135deg,{v.sweep[0]},{v.sweep[1]})"
        if isinstance(paint, tuple):
            c0 = INK if paint[0] == "ink" else paint[0]
            c1 = INK if paint[1] == "ink" else paint[1]
            return f"linear-gradient(90deg,{c0},{c1})"
        return INK if paint == "ink" else paint

    return (
        '<span class="rings">'
        + "".join(f'<i style="background:{css(p)}"></i>' for p in v.rings)
        + "</span>"
    )


def gallery(variants: list[Variant]) -> str:
    swatches = "".join(
        f'<span class="swatch"><i style="background:{hexv}"></i>{name} {hexv}</span>'
        for name, hexv in (
            ("ink", INK),
            ("sage", SAGE),
            ("dusk", DUSK),
            ("clay", CLAY),
            ("ochre", OCHRE),
            ("mauve", MAUVE),
            ("paper", PAPER),
            ("slate", SLATE),
        )
    )
    # the dark-scheme fills of every travelling ring, for the slate boards
    dark_css = "".join(
        f".board.slate .{s.cls}{{fill:{s.dark}}}"
        for v in variants
        for s in render_variant(v)
        if s.dark
    )
    cards = []
    for i, v in enumerate(variants, 1):
        sizes = "".join(
            f"<figure>{svg_use(v, px)}<figcaption>{px}px</figcaption></figure>"
            for px in (96, 48, 24, 16)
        )
        made = (
            "one linear gradient (userSpaceOnUse, top-left to bottom-right) shared by the three strokes"
            if v.sweep
            else f"each stroke in {CHUNKS} pieces, the colour blended in OKLab from where the brush lands to where it lifts"
            if v.gradient
            else "three flat fills; ink is currentColor and follows the ground"
        )
        cards.append(
            f'<section class="option" id="{v.slug}-card">\n'
            f'<header><span class="n">{i} · <code>{v.slug}.svg</code></span><h2>{v.name}</h2>{ring_swatches(v)}</header>\n'
            f'<p class="note">{v.note[0].upper() + v.note[1:]}.</p>\n'
            f'<div class="boards">\n'
            f'<div class="board paper">{svg_use(v, 220)}</div>\n'
            f'<div class="board slate">{svg_use(v, 220)}</div>\n'
            f'<div class="board paper sizes">{sizes}</div>\n'
            f"</div>\n"
            f'<div class="lockup">{svg_use(v, 40)}<span>the-loop</span></div>\n'
            f'<p class="made">Drawn as: {made}.</p>\n'
            f"</section>"
        )
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>the-loop — the Ensō in colourways, round 3 (issue-398)</title>\n"
        f"<style>{GALLERY_CSS}{dark_css}</style>\n</head>\n<body>\n"
        f'<svg class="defs" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">{"".join(svg_symbol(v) for v in variants)}</svg>\n'
        "<main>\n"
        "<h1>the-loop — the Ensō, in colourways</h1>\n"
        '<p class="lede">Round 3. The owner chose the Ensō — three brush circles, each left open where the hand lifted: the '
        "outer loop, the inner loop, and the one between — and asked for colour and gradient options. The mark is the same "
        "in every card; only the paint changes: seven flat palettes, a gradient that travels along each stroke, an "
        "ink-to-accent that runs dry, and one sweep across the whole mark. Shown on paper, on slate, at four sizes down "
        "to a favicon, and beside the name. Pick one on the ticket; a different pairing is a parameter change and a re-run.</p>\n"
        f'<div class="palette">{swatches}</div>\n' + "\n".join(cards) + "\n<footer>\n"
        "<p>Source: <code>docs/specs/issue-398/design/generate.py</code> — stdlib Python, no dependencies. "
        "<code>python3 generate.py</code> rewrites every file here; <code>python3 generate.py --check</code> "
        "verifies the files on disk are exactly what the script makes, well-formed and self-contained. "
        "Rounds 1 and 2 are in the git history of this folder.</p>\n"
        "</footer>\n</main>\n</body>\n</html>\n"
    )


# ------------------------------------------------------------------- the adopted mark

ADOPTED = "enso-5-dusk-sage-ink"  # the owner's pick — PR #403 review, 2026-09-21
REPO = HERE.parents[3]  # docs/specs/issue-398/design → the repository root

# Where the mark lives once adopted. A path with a slash is relative to the repository
# root; the design folder's own outputs stay bare names.
ADOPTED_FILES = {
    "docs/assets/the-loop-logo.svg": "auto",  # README and anything that follows the ground
    "docs/assets/the-loop-logo-light.svg": "light",  # GitHub's <picture>, light source
    "docs/assets/the-loop-logo-dark.svg": "dark",  # GitHub's <picture>, dark source
    "docs/public/favicon.svg": "auto",  # the docs site's favicon
    "docs/public/logo-light.svg": "light",  # the site's nav and hero, light theme
    "docs/public/logo-dark.svg": "dark",  # the site's nav and hero, dark theme
    "ui/public/favicon.svg": "auto",  # the control-plane dashboard's favicon
}


def adopted() -> Variant:
    return next(v for v in VARIANTS if v.slug == ADOPTED)


def logo_file(mode: str) -> str:
    """The adopted mark as a brand asset. `auto` follows the ground (currentColor ink,
    swapped by the dark-scheme rule); `light` and `dark` fix the ink for a surface that
    switches themes itself — GitHub's <picture>, the docs site's theme toggle — where an
    OS-driven media rule would disagree with the page. The adopted colourway is flat, so
    fixing the ink is one substitution; a travelling colourway would need its dark
    piece fills baked the same way."""
    v = adopted()
    body = svg_body(v)
    style = ""
    if mode == "auto":
        style = f"<style>@media (prefers-color-scheme:dark){{svg{{color:{INK_ON_SLATE}}}{dark_rules(v)}}}</style>\n"
    else:
        ink = INK if mode == "light" else INK_ON_SLATE
        body = body.replace('fill="currentColor"', f'fill="{ink}"')
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}" '
        f'color="{INK}" role="img" aria-labelledby="the-loop-logo-title the-loop-logo-desc">\n'
        '<title id="the-loop-logo-title">the-loop</title>\n'
        '<desc id="the-loop-logo-desc">the-loop\'s mark: three brush circles, each left open where the hand lifted — the outer loop, the inner loop, and the one between; '
        f"{v.name}. Generated by docs/specs/issue-398/design/generate.py.</desc>\n"
        f"{style}{body}\n</svg>\n"
    )


def target(name: str) -> Path:
    return REPO / name if "/" in name else HERE / name


# ------------------------------------------------------------------------------ main


def render() -> dict[str, str]:
    files = {f"{v.slug}.svg": svg_file(v) for v in VARIANTS}
    files["logo-options.html"] = gallery(VARIANTS)
    for name, mode in ADOPTED_FILES.items():
        files[name] = logo_file(mode)
    return files


SVG_NS = "{http://www.w3.org/2000/svg}"
# What a generated SVG may contain — parsed and compared, never grepped. Anything else
# (a script, an image, an event handler, an animation, a link) fails the check.
SVG_ELEMENTS = {"svg", "title", "desc", "style", "path", "linearGradient", "stop"}
SVG_ATTRIBUTES = {
    "viewBox",
    "color",
    "role",
    "aria-labelledby",
    "id",
    "d",
    "fill",
    "class",
    "gradientUnits",
    "x1",
    "y1",
    "x2",
    "y2",
    "offset",
    "stop-color",
}
# The gallery is HTML, so it is scanned: the same absences, and only fragment references.
FORBIDDEN = (
    "<script",
    "<foreignObject",
    "<image",
    "<iframe",
    "<object",
    "<embed",
    "<link",
    "<base",
    "<meta http-equiv",
    "@import",
    "src=",
    "javascript:",
)
HANDLER = re.compile(r"\bon[a-z]+\s*=", re.I)  # onclick=, onload=, …
EXTERNAL_REF = re.compile(r"""(?i)(href|url)\s*[=(]\s*(?!["']?#)""")


def svg_problems(name: str, root: ET.Element) -> list[str]:
    """Everything a standalone SVG may not carry, from its parsed tree."""
    out: list[str] = []
    for el in root.iter():
        tag = el.tag.removeprefix(SVG_NS)
        if tag not in SVG_ELEMENTS:
            out.append(f"{name}: element <{tag}> is not in the allowlist")
        for attr, value in el.attrib.items():
            if attr not in SVG_ATTRIBUTES:
                out.append(
                    f"{name}: attribute {attr!r} on <{tag}> is not in the allowlist"
                )
            elif EXTERNAL_REF.search(value):
                out.append(f"{name}: {attr} reference {value!r} is not a fragment")
    for style in root.iter(f"{SVG_NS}style"):
        if EXTERNAL_REF.search(style.text or "") or "@import" in (style.text or ""):
            out.append(f"{name}: the stylesheet references something outside the file")
    return out


def check(files: dict[str, str]) -> list[str]:
    problems: list[str] = []
    for name, content in files.items():
        path = target(name)
        if not path.exists():
            problems.append(f"{name}: missing")
            continue
        if path.read_text(encoding="utf-8") != content:
            problems.append(
                f"{name}: differs from what generate.py produces (re-run it)"
            )
        if name.endswith(".svg"):
            try:
                root = ET.fromstring(content)
            except ET.ParseError as e:
                problems.append(f"{name}: not well-formed XML ({e})")
                continue
            if (
                root.find(f"{SVG_NS}title") is None
                or root.find(f"{SVG_NS}desc") is None
            ):
                problems.append(f"{name}: missing <title> or <desc>")
            if len(content.encode()) > 64_000:
                problems.append(f"{name}: over 64 kB")
            problems += svg_problems(name, root)
        else:
            for token in FORBIDDEN:
                if token.lower() in content.lower():
                    problems.append(f"{name}: contains {token!r}")
            if HANDLER.search(content):
                problems.append(f"{name}: has an event-handler attribute")
            if EXTERNAL_REF.search(content):
                problems.append(f"{name}: has an href or url() that is not a fragment")
    if render() != files:
        problems.append("generate.py is not deterministic")
    return problems


def main(argv: list[str]) -> int:
    files = render()
    if "--check" in argv:
        problems = check(files)
        for p in problems:
            print(f"FAIL {p}")
        if not problems:
            print(f"ok — {len(files)} files match, well-formed, self-contained, titled")
        return 1 if problems else 0
    for name, content in files.items():
        target(name).parent.mkdir(parents=True, exist_ok=True)
        target(name).write_text(content, encoding="utf-8")
        print(f"wrote {name} ({len(content.encode()) / 1000:.1f} kB)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
