#!/usr/bin/env python3
# ruff: noqa: E501 — the strings are prose and CSS; wrapping them would not help a reader
"""the-loop logo options (issue-398): five hand-drawn SVG marks from one generator.

Usage:

    python3 generate.py            write the five SVGs and the gallery next to this file
    python3 generate.py --check    verify the files on disk are exactly what this script
                                   makes, well-formed, self-contained and titled

Standard library only. Every mark is built from *ribbons*: a centreline sampled from a
parametric curve, pushed sideways by seeded low-frequency noise (the wobble of a hand),
then outlined with a width that swells and tapers (the pressure of a pen). The outline
is a closed, filled path — nothing depends on stroke rendering, filters or fonts, so the
files render the same in a browser, a README, a favicon and an image tool. Change a
parameter, re-run, and every file is regenerated byte-for-byte.
"""

from __future__ import annotations

import math
import random
import re
import sys
import xml.etree.ElementTree as ET
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIZE = 256.0
C = SIZE / 2

# The palette: one warm ink, five muted accents, paper and slate for the two grounds.
INK = "#3f3a33"
INK_ON_SLATE = "#e9e3d7"
PAPER = "#f5f0e6"
SLATE = "#22252a"
SAGE = "#8a9c84"
DUSK = "#7f93a5"
CLAY = "#c48a6c"
OCHRE = "#c7a86b"
MAUVE = "#9d8a9f"

Point = tuple[float, float]
Curve = Callable[[float], Point]
Width = Callable[[float], float]


# --------------------------------------------------------------------------- geometry


def fmt(p: Point) -> str:
    return f"{p[0]:.1f} {p[1]:.1f}"


def smoothstep(x: float) -> float:
    x = min(1.0, max(0.0, x))
    return x * x * (3 - 2 * x)


class Wobble:
    """Seeded sideways noise: a few integer harmonics of the loop's own period, so a
    closed loop's wobble is seamless where it meets itself."""

    def __init__(self, rng: random.Random, amp: float, harmonics=(2, 3, 5)) -> None:
        self.terms = [
            (amp / (i + 1), h, rng.uniform(0, math.tau))
            for i, h in enumerate(harmonics)
        ]

    def __call__(self, u: float) -> float:
        return sum(a * math.sin(math.tau * h * u + p) for a, h, p in self.terms)


def trace(
    curve: Curve,
    u0: float,
    u1: float,
    n: int,
    wobble: Wobble | None = None,
    drift: float = 0.0,
) -> list[Point]:
    """Sample `curve` on [u0, u1], pushing each sample along its normal by the wobble.
    `drift` eases the last stretch of an overshooting loop outward, so the closing
    stroke lands beside the opening one instead of exactly on it."""
    pts: list[Point] = []
    for i in range(n + 1):
        u = u0 + (u1 - u0) * i / n
        x, y = curve(u)
        ax, ay = curve(u - 1e-3)
        bx, by = curve(u + 1e-3)
        tx, ty = bx - ax, by - ay
        norm = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / norm, tx / norm
        off = wobble(u) if wobble else 0.0
        if drift:
            off += drift * smoothstep((u - u0 - 0.82) / (u1 - u0 - 0.82))
        pts.append((x + nx * off, y + ny * off))
    return pts


def spline(pts: list[Point], closed: bool) -> str:
    """Catmull-Rom through the points, emitted as cubic Béziers."""
    n = len(pts)

    def at(i: int) -> Point:
        return pts[i % n] if closed else pts[min(max(i, 0), n - 1)]

    out = [f"M{fmt(pts[0])}"]
    for i in range(n if closed else n - 1):
        p0, p1, p2, p3 = at(i - 1), at(i), at(i + 1), at(i + 2)
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        out.append(f"C{fmt(c1)} {fmt(c2)} {fmt(p2)}")
    out.append("Z")
    return "".join(out)


def outline(pts: list[Point], width: Width, closed: bool) -> str:
    """The filled outline of a variable-width ribbon along `pts`."""
    if closed:
        pts = pts[:-1]
    n = len(pts)
    left: list[Point] = []
    right: list[Point] = []
    for i, (x, y) in enumerate(pts):
        if closed:
            (ax, ay), (bx, by) = pts[(i - 1) % n], pts[(i + 1) % n]
        else:
            (ax, ay), (bx, by) = pts[max(i - 1, 0)], pts[min(i + 1, n - 1)]
        tx, ty = bx - ax, by - ay
        norm = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / norm, tx / norm
        w = width(i / (n - 1)) / 2
        left.append((x + nx * w, y + ny * w))
        right.append((x - nx * w, y - ny * w))
    if closed:
        return spline(left, True) + spline(right[::-1], True)
    return spline(left + right[::-1], True)


def pen(
    rng: random.Random, base: float, swell: float = 0.3, taper: float = 0.0
) -> Width:
    """A pen whose pressure swells once around the loop and tapers at the ends."""
    p1, p2 = rng.uniform(0, math.tau), rng.uniform(0, math.tau)

    def width(u: float) -> float:
        w = base * (
            1
            + swell * math.sin(math.tau * u + p1)
            + 0.12 * math.sin(3 * math.tau * u + p2)
        )
        if taper:
            w *= 0.15 + 0.85 * smoothstep(min(u, 1 - u) / taper)
        return max(w, 0.5)

    return width


# ----------------------------------------------------------------------------- curves


def ellipse(cx: float, cy: float, rx: float, ry: float, rot_deg: float = 0.0) -> Curve:
    r = math.radians(rot_deg)
    cr, sr = math.cos(r), math.sin(r)

    def f(u: float) -> Point:
        t = math.tau * u
        x, y = rx * math.cos(t), ry * math.sin(t)
        return (cx + x * cr - y * sr, cy + x * sr + y * cr)

    return f


def circle(cx: float, cy: float, r: float) -> Curve:
    return ellipse(cx, cy, r, r)


def epitrochoid(
    cx: float,
    cy: float,
    big: float,
    small: float,
    d: float,
    scale: float,
    rot_deg: float = 0.0,
) -> Curve:
    """A point at distance `d` from the centre of a circle of radius `small` rolling
    around the outside of a circle of radius `big`. With d > small the point loops
    back on itself once per revolution of the small circle — big/small loops, all
    pointing inward, drawn in one continuous line."""
    k = (big + small) / small
    r = math.radians(rot_deg)
    cr, sr = math.cos(r), math.sin(r)

    def f(u: float) -> Point:
        t = math.tau * u
        x = ((big + small) * math.cos(t) - d * math.cos(k * t)) * scale
        y = ((big + small) * math.sin(t) - d * math.sin(k * t)) * scale
        return (cx + x * cr - y * sr, cy + x * sr + y * cr)

    return f


def rotate(p: Point, cx: float, cy: float, deg: float) -> Point:
    r = math.radians(deg)
    x, y = p[0] - cx, p[1] - cy
    return (
        cx + x * math.cos(r) - y * math.sin(r),
        cy + x * math.sin(r) + y * math.cos(r),
    )


# ---------------------------------------------------------------------------- strokes


@dataclass
class Ribbon:
    d: str
    fill: str
    opacity: float = 1.0
    cls: str = ""

    def svg(self, blend: str | None = None) -> str:
        """`blend` renders a `blend`-classed ribbon with that mix-blend-mode inline
        (for a gallery symbol); None keeps the class for the standalone stylesheet."""
        fill = "currentColor" if self.fill == INK else self.fill
        attrs = [f'd="{self.d}"', f'fill="{fill}"', 'fill-rule="evenodd"']
        if self.cls == "blend" and blend:
            attrs.insert(0, f'style="mix-blend-mode:{blend}"')
        elif self.cls:
            attrs.insert(0, f'class="{self.cls}"')
        if self.opacity < 1:
            attrs.append(f'opacity="{self.opacity:.2f}"')
        return f"<path {' '.join(attrs)}/>"


def stroke(
    curve: Curve,
    rng: random.Random,
    *,
    fill: str,
    width: float,
    samples: int = 96,
    wobble: float = 1.8,
    swell: float = 0.3,
    start: float = 0.0,
    overshoot: float | None = 0.06,
    drift: float = 1.6,
    sketch: bool = True,
    cls: str = "",
    opacity: float = 1.0,
) -> list[Ribbon]:
    """Draw `curve` as a hand-drawn ribbon.

    overshoot=None  — a seamless closed band (no visible join).
    overshoot=x     — one open stroke from `start` all the way round and x further, its
                      ends tapered: the loop is closed the way a hand closes it.
    sketch          — a second, thinner, fainter pass over part of the loop.
    """
    out: list[Ribbon] = []
    if overshoot is None:
        pts = trace(curve, 0.0, 1.0, samples, Wobble(rng, wobble))
        out.append(
            Ribbon(outline(pts, pen(rng, width, swell), True), fill, opacity, cls)
        )
    else:
        u1 = start + 1.0 + overshoot
        pts = trace(curve, start, u1, samples, Wobble(rng, wobble), drift)
        out.append(
            Ribbon(
                outline(pts, pen(rng, width, swell, taper=0.05), False),
                fill,
                opacity,
                cls,
            )
        )
    if sketch:
        a = start + rng.uniform(0.05, 0.5)
        span = rng.uniform(0.3, 0.55)
        pts = trace(
            curve, a, a + span, max(24, int(samples * span)), Wobble(rng, wobble * 1.4)
        )
        out.append(
            Ribbon(
                outline(pts, pen(rng, width * 0.5, 0.2, taper=0.12), False),
                fill,
                opacity * 0.45,
                cls,
            )
        )
    return out


def dot(
    cx: float, cy: float, r: float, rng: random.Random, *, fill: str, cls: str = ""
) -> Ribbon:
    pts = trace(circle(cx, cy, r * 0.55), 0.0, 1.0, 32, Wobble(rng, r * 0.08))
    return Ribbon(outline(pts, lambda _u: r * 0.9, True), fill, 1.0, cls)


# ---------------------------------------------------------------------------- options


@dataclass
class Option:
    slug: str
    name: str
    concept: str
    meaning: list[str]
    made_of: str
    ribbons: list[Ribbon]
    style: str = ""  # extra CSS the standalone file (and the gallery) carries


def option_gimbal() -> Option:
    rng = random.Random(398_1)
    ribbons: list[Ribbon] = []
    ribbons += stroke(
        ellipse(C, C + 2, 102, 97, -8),
        rng,
        fill=INK,
        width=5.8,
        samples=104,
        wobble=2.2,
    )
    ribbons += stroke(
        ellipse(C - 2, C + 1, 78, 40, 27),
        rng,
        fill=DUSK,
        width=4.6,
        samples=96,
        start=0.3,
    )
    ribbons += stroke(
        ellipse(C + 1, C - 1, 32, 44, -34),
        rng,
        fill=CLAY,
        width=4.2,
        samples=80,
        start=0.6,
    )
    ribbons.append(dot(C, C, 5.0, rng, fill=INK))
    return Option(
        "option-1-gimbal",
        "Gimbal",
        "Nested loops that turn on one centre.",
        [
            "The outer ring is the work item's loop; the two rings inside it are the loops it carries, each at its own tilt.",
            "The dot is the ticket — the one fixed point every loop turns on.",
            "Three ellipses, three tilts, one pivot: an armillary sphere drawn by hand.",
        ],
        "three tilted ellipses and a dot, each ribbon a seeded wobble and a swelling pen; 4 ribbons + 3 sketch passes",
        ribbons,
    )


def option_one_line() -> Option:
    rng = random.Random(398_2)
    curve = epitrochoid(C, C, 3.0, 1.0, 2.15, 16.4, -90)
    ribbons = stroke(
        curve,
        rng,
        fill=INK,
        width=5.4,
        samples=240,
        wobble=1.4,
        start=0.18,
        overshoot=0.05,
        drift=1.2,
    )
    ribbons.append(dot(C, C, 4.2, rng, fill=CLAY))
    return Option(
        "option-2-one-line",
        "One line",
        "One continuous stroke: an outer loop that dips inward to make three inner loops and returns to close.",
        [
            "The pen never lifts — the outer loop and the inner loops are one process, not several.",
            "Three inner loops meet at the centre: the pull requests, each a loop of its own, all part of the same line.",
            "The dot is the ticket the line is drawn around.",
        ],
        "an epitrochoid (a circle of radius 1 rolling around a circle of radius 3, tracing a point 2.15 out), one ribbon, tapered where the hand starts and stops",
        ribbons,
    )


def option_coil() -> Option:
    rng = random.Random(398_3)
    coil = epitrochoid(C, C, 18.0, 1.0, 1.5, 5.05, 0)
    ribbons = stroke(
        coil,
        rng,
        fill=INK,
        width=3.4,
        samples=396,
        wobble=0.9,
        swell=0.2,
        start=0.02,
        overshoot=0.03,
        drift=0.0,
        sketch=False,
    )
    ribbons += stroke(
        ellipse(C + 3, C + 2, 42, 38, 15),
        rng,
        fill=SAGE,
        width=4.4,
        samples=90,
        start=0.4,
    )
    ribbons.append(dot(C, C, 4.2, rng, fill=CLAY))
    return Option(
        "option-3-coil",
        "Coil",
        "A loop whose line is itself made of loops.",
        [
            "The outer loop is not a line but a coil — eighteen small loops, one continuous path: loops all the way down.",
            "Inside it, one plain loop: the inner loop the outer one carries.",
            "The dot is the ticket at the centre.",
        ],
        "an epitrochoid with eighteen inward loops (a circle of radius 1 around one of radius 18, tracing a point 1.5 out) as one thin ribbon, plus one plain ring",
        ribbons,
    )


def option_rings() -> Option:
    rng = random.Random(398_4)
    ribbons: list[Ribbon] = []
    ribbons += stroke(
        ellipse(C - 6, C + 8, 88, 84, 10),
        rng,
        fill=DUSK,
        width=11,
        samples=110,
        wobble=2.4,
        swell=0.45,
        overshoot=None,
        sketch=False,
        cls="blend",
        opacity=0.85,
    )
    ribbons += stroke(
        ellipse(C + 30, C - 26, 58, 54, -20),
        rng,
        fill=CLAY,
        width=10,
        samples=100,
        wobble=2.2,
        swell=0.45,
        overshoot=None,
        sketch=False,
        cls="blend",
        opacity=0.85,
    )
    ribbons += stroke(
        ellipse(C - 26, C - 30, 40, 44, 30),
        rng,
        fill=SAGE,
        width=9,
        samples=90,
        wobble=2.0,
        swell=0.45,
        overshoot=None,
        sketch=False,
        cls="blend",
        opacity=0.85,
    )
    ribbons += stroke(
        ellipse(C + 12, C + 34, 34, 30, -10),
        rng,
        fill=OCHRE,
        width=8.5,
        samples=90,
        wobble=1.8,
        swell=0.45,
        overshoot=None,
        sketch=False,
        cls="blend",
        opacity=0.85,
    )
    return Option(
        "option-4-rings",
        "Rings",
        "Many loops overlapping; where they overlap, the colour deepens — that is where the work happens.",
        [
            "One large loop and three smaller ones, each translucent, laid over each other like rings left on a table.",
            "Every overlap makes a colour none of the loops has alone: the loops working together are visible as new colour.",
            "No loop is complete without the others — the large one holds them, the small ones give it its shape.",
        ],
        "four wobbly bands at 85% opacity, blended with `multiply` on paper and `screen` on slate (plain alpha where a renderer has neither)",
        ribbons,
        style=".blend{mix-blend-mode:multiply}",
    )


def option_planetary() -> Option:
    rng = random.Random(398_5)
    ribbons: list[Ribbon] = []
    ring = circle(C, C, 101)
    ribbons += stroke(ring, rng, fill=INK, width=5.8, samples=100)
    sun = circle(C, C, 40)
    ribbons += stroke(sun, rng, fill=OCHRE, width=4.6, samples=72, start=0.5)
    for angle, color in ((-90, DUSK), (30, SAGE), (150, CLAY)):
        cx, cy = rotate((C, C - 70), C, C, angle + 90)
        planet = circle(cx, cy, 27)
        ribbons += stroke(
            planet, rng, fill=color, width=4.2, samples=64, start=rng.uniform(0, 1)
        )
    return Option(
        "option-5-planetary",
        "Planetary",
        "Loops that drive loops: an outer ring, three planets inside it, a sun at the centre — a planetary gear drawn as loops.",
        [
            "The outer ring is the work item's loop; the three loops meshing with it are the pull requests, turning as it turns.",
            "The sun in the middle is the ticket every planet also meshes with.",
            "Each planet touches both the ring and the sun: no loop turns alone.",
        ],
        "five circles in the proportions of a planetary gear set (ring 101, planets 27 at radius 70, sun 40)",
        ribbons,
    )


OPTIONS: list[Callable[[], Option]] = [
    option_gimbal,
    option_one_line,
    option_coil,
    option_rings,
    option_planetary,
]


# ------------------------------------------------------------------------------- svg


def svg_body(opt: Option, blend: str | None = None) -> str:
    return "\n".join(r.svg(blend) for r in opt.ribbons)


def svg_file(opt: Option) -> str:
    """The standalone file. The ink is `currentColor`, set once on the root and swapped
    for the dark-scheme ink by the one media rule; accents are mid-toned enough for
    either ground. A blended option carries its two blend modes the same way."""
    title = f"the-loop — {opt.name}"
    dark = f"svg{{color:{INK_ON_SLATE}}}" + (
        ".blend{mix-blend-mode:screen}" if opt.style else ""
    )
    style = f"{opt.style}@media (prefers-color-scheme:dark){{{dark}}}"
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}" '
        f'color="{INK}" role="img" aria-labelledby="{opt.slug}-title {opt.slug}-desc">\n'
        f'<title id="{opt.slug}-title">{title}</title>\n'
        f'<desc id="{opt.slug}-desc">{opt.concept} Generated by docs/specs/issue-398/design/generate.py.</desc>\n'
        f"<style>{style}</style>\n"
        f"{svg_body(opt)}\n"
        "</svg>\n"
    )


def symbol_id(opt: Option, ground: str) -> str:
    return f"{opt.slug}-{ground}" if opt.style else opt.slug


def svg_symbols(opt: Option) -> str:
    """One <symbol> per option for the gallery to <use>; a blended option gets one per
    ground, since a mix-blend-mode cannot follow the <use> element's context."""
    if not opt.style:
        return f'<symbol id="{opt.slug}" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}">{svg_body(opt)}</symbol>'
    return "".join(
        f'<symbol id="{symbol_id(opt, ground)}" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}">{svg_body(opt, mode)}</symbol>'
        for ground, mode in (("paper", "multiply"), ("slate", "screen"))
    )


def svg_use(opt: Option, px: int, ground: str = "paper") -> str:
    return f'<svg width="{px}" height="{px}" aria-hidden="true"><use href="#{symbol_id(opt, ground)}"/></svg>'


# --------------------------------------------------------------------------- gallery


GALLERY_CSS = (
    """
:root{--paper:@paper;--slate:@slate;--ink:@ink;--ink-slate:@ink_slate;--rule:#d9d2c4;--muted:#7a736a}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;padding:32px 16px 64px}
main{max-width:1080px;margin:0 auto}
h1{font-size:26px;margin:0 0 6px;letter-spacing:-.01em}
h2{font-size:20px;margin:0}
p{margin:0 0 8px}
.lede{color:var(--muted);max-width:70ch;margin-bottom:24px}
.palette{display:flex;flex-wrap:wrap;gap:10px;margin:0 0 36px}
.swatch{display:flex;align-items:center;gap:8px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.swatch i{width:22px;height:22px;border-radius:50%;border:1px solid var(--rule);display:inline-block}
.option{border-top:1px solid var(--rule);padding:28px 0 36px}
.option header{display:flex;flex-wrap:wrap;align-items:baseline;gap:6px 14px;margin-bottom:6px}
.option .n{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.concept{font-size:17px;max-width:70ch;margin-bottom:16px}
.boards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin-bottom:16px}
.board{border-radius:14px;padding:18px;display:flex;align-items:center;justify-content:center;min-height:256px;border:1px solid var(--rule)}
.board.paper{background:var(--paper);color:var(--ink)}
.board.slate{background:var(--slate);border-color:#3a3e45;color:var(--ink-slate)}
.defs{position:absolute;width:0;height:0;overflow:hidden}
.board.sizes{flex-direction:row;gap:22px;align-items:flex-end;flex-wrap:wrap}
.board.sizes figure{margin:0;display:flex;flex-direction:column;align-items:center;gap:6px}
.board.sizes figcaption{font:11px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
.lockup{display:flex;align-items:center;gap:12px;font:600 26px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:-.02em;margin:0 0 18px;color:var(--ink)}
@media (prefers-color-scheme:dark){.lockup{color:var(--ink-slate)}}
.meaning{margin:0 0 10px;padding-left:20px;max-width:80ch}
.meaning li{margin:0 0 4px}
.made{color:var(--muted);font-size:13px;max-width:80ch}
.made code{font:12px ui-monospace,SFMono-Regular,Menlo,monospace}
footer{border-top:1px solid var(--rule);padding-top:18px;color:var(--muted);font-size:13px}
footer code{font:12px ui-monospace,SFMono-Regular,Menlo,monospace}
@media (prefers-color-scheme:dark){
  body{background:var(--slate);color:var(--ink-slate)}
  :root{--rule:#3a3e45;--muted:#a49d92}
  .board.paper{background:var(--paper);color:var(--ink)}
}
""".replace("@paper", PAPER)
    .replace("@slate", SLATE)
    .replace("@ink_slate", INK_ON_SLATE)
    .replace("@ink", INK)
)


def gallery(options: list[Option]) -> str:
    swatches = "".join(
        f'<span class="swatch"><i style="background:{hexv}"></i>{name} {hexv}</span>'
        for name, hexv in (
            ("ink", INK),
            ("sage", SAGE),
            ("dusk", DUSK),
            ("clay", CLAY),
            ("ochre", OCHRE),
            ("mauve", MAUVE),
            ("paper", PAPER),
            ("slate", SLATE),
        )
    )
    cards = []
    for i, opt in enumerate(options, 1):
        sizes = "".join(
            f"<figure>{svg_use(opt, px)}<figcaption>{px}px</figcaption></figure>"
            for px in (96, 48, 24, 16)
        )
        meaning = "".join(f"<li>{m}</li>" for m in opt.meaning)
        cards.append(
            f'<section class="option" id="{opt.slug}">\n'
            f'<header><span class="n">option {i} · <code>{opt.slug}.svg</code></span><h2>{opt.name}</h2></header>\n'
            f'<p class="concept">{opt.concept}</p>\n'
            f'<div class="boards">\n'
            f'<div class="board paper">{svg_use(opt, 220)}</div>\n'
            f'<div class="board slate">{svg_use(opt, 220, "slate")}</div>\n'
            f'<div class="board paper sizes">{sizes}</div>\n'
            f"</div>\n"
            f'<div class="lockup">{svg_use(opt, 40)}<span>the-loop</span></div>\n'
            f'<ul class="meaning">{meaning}</ul>\n'
            f'<p class="made">Drawn as: {opt.made_of}.</p>\n'
            f"</section>"
        )
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>the-loop — logo options (issue-398)</title>\n"
        f"<style>{GALLERY_CSS}</style>\n</head>\n<body>\n"
        f'<svg class="defs" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">{"".join(svg_symbols(o) for o in options)}</svg>\n'
        "<main>\n"
        "<h1>the-loop — logo options</h1>\n"
        '<p class="lede">Five marks, five concepts of <em>inner, outer and many loops working together</em>. '
        "Each is one standalone SVG, hand-drawn by a generator (a seeded wobble along every loop, a pen that swells "
        "and tapers), in one muted palette. Shown on paper, on slate, at four sizes down to a favicon, and beside the name. "
        "Pick one on the ticket; feedback becomes a parameter change and a re-run.</p>\n"
        f'<div class="palette">{swatches}</div>\n' + "\n".join(cards) + "\n<footer>\n"
        "<p>Source: <code>docs/specs/issue-398/design/generate.py</code> — stdlib Python, no dependencies. "
        "<code>python3 generate.py</code> rewrites every file here; <code>python3 generate.py --check</code> "
        "verifies the files on disk are exactly what the script makes, well-formed and self-contained.</p>\n"
        "</footer>\n</main>\n</body>\n</html>\n"
    )


# ------------------------------------------------------------------------------ main


def render() -> dict[str, str]:
    options = [make() for make in OPTIONS]
    files = {f"{opt.slug}.svg": svg_file(opt) for opt in options}
    files["logo-options.html"] = gallery(options)
    return files


FORBIDDEN = (
    "<script",
    "<foreignObject",
    "<image",
    "<iframe",
    "url(",
    "@import",
    "src=",
)
EXTERNAL_HREF = re.compile(r'href="(?!#)')  # a fragment is the gallery's own <use>


def check(files: dict[str, str]) -> list[str]:
    problems: list[str] = []
    for name, content in files.items():
        path = HERE / name
        if not path.exists():
            problems.append(f"{name}: missing")
            continue
        if path.read_text(encoding="utf-8") != content:
            problems.append(
                f"{name}: differs from what generate.py produces (re-run it)"
            )
        if name.endswith(".svg"):
            try:
                root = ET.fromstring(content)
            except ET.ParseError as e:
                problems.append(f"{name}: not well-formed XML ({e})")
                continue
            ns = "{http://www.w3.org/2000/svg}"
            if root.find(f"{ns}title") is None or root.find(f"{ns}desc") is None:
                problems.append(f"{name}: missing <title> or <desc>")
            if len(content.encode()) > 40_000:
                problems.append(f"{name}: over 40 KB")
        for token in FORBIDDEN:
            if token in content:
                problems.append(f"{name}: contains {token!r}")
        if EXTERNAL_HREF.search(content):
            problems.append(f"{name}: has an href that is not a fragment")
    if render() != files:
        problems.append("generate.py is not deterministic")
    return problems


def main(argv: list[str]) -> int:
    files = render()
    if "--check" in argv:
        problems = check(files)
        for p in problems:
            print(f"FAIL {p}")
        if not problems:
            print(f"ok — {len(files)} files match, well-formed, self-contained, titled")
        return 1 if problems else 0
    for name, content in files.items():
        (HERE / name).write_text(content, encoding="utf-8")
        print(f"wrote {name} ({len(content.encode()) / 1000:.1f} kB)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
